blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('polls/', include('polls.urls')),
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title','text')

blog/views.py
from pyexpat.errors import messages

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Post
from .forms import PostForm
from django.core.paginator import Paginator

# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    search_key = request.GET.get('search_key')
    if search_key:
        posts = posts.filter(title__icontains=search_key)
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()

    return render(request, 'blog/post_edit.html', {'form':form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, 'blog/post_edit.html', {'form':form})

@login_required(login_url='common:login')
def post_delete(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.user != post.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('blog:post_detail', pk=post.pk)
    post.delete()
    return redirect('blog:post_list')

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}
Post Detail
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

<div class="page-header" style="background-color: #B0C1DB">
    {% if user.is_authenticated %}
    <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
    {% endif %}
    <h1><a href="{% url 'blog:post_list' %}">HYWU Blog</a> </h1>
</div>
   <div class="post">
       {% if post.published_date %}
          <div class="date">
          {{post.published_date}}
          </div>
       {% endif %}

       {% if user.is_authenticated %}
       <a class="btn btn-sm btn-outline-secondary" href="{% url 'blog:post_edit' pk=post.pk %}">
           <span style="font-size: 3.3em;" class="glyphicon glyphicon-pencil"></span></a>
       <a href="#" class="delete btn btn-sm btn-outline-secondary"
       data-uri="{% url 'blog:post_delete' pk=post.pk  %}"><span style="font-size: 3.5em;" class="glyphicon glyphicon-trash"></span></a>
       {% endif %}

       <h1>{{post.title}} </h1>
       <p>{{post.text|linebreaksbr}}</p>

   </div>

{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}

{% block title %}
Post Edit
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

<div class="page-header" style="background-color: #B0C1DB">
    {% if user.is_authenticated %}
    <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
    {% endif %}
    <h1><a href="{% url 'blog:post_list' %}">HYWU Blog</a> </h1>
</div>
<h1>New post</h1>
<form method="POST" class="post-form">

{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Save</button>
</form>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block title %}
Post List
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<meta charset="UTF-8">
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

<div class="page-header" style="background-color: #B0C1DB">
    {% if user.is_authenticated %}
    <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
    {% endif %}
    <h1><a href="{% url 'blog:post_list' %}">Happy Blog's Day</a> </h1>
</div>
<form action="" method='GET'>
    <div class="row" style="margin-bottom:15px;">
        <div class="col-lg-5">
            <div class="input-group">
                <input type="text" class="form-control" name="search_key" value="{{ search_key }}"
                    placeholder="Search">
                <span class="input-group-btn">
                    <input class="btn btn-default" type="submit" value="Search">
                </span>
            </div>
        </div>
    </div>
</form>

<div class="row">
    <div id="post_list_search" class="col-md-12">
        {% for blog in post_list %}
        <a href="{% url 'blog:post_list' %}">
            <h4>{{ post.title }}</h4>
        </a>
        {% endfor %}
    </div>
</div>

{% for post in posts %}
   <div class="post">
      <div class="date">
       <p>published: {{post.published_date}}</p>
       </div>
       <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a> </h1>
       <p>{{post.text|linebreaksbr}}</p>
   </div>
{% endfor %}


{% endblock %}